### ISSUE TITLE
logstash.status missing

### ISSUE THREAD

**Issue by Protocol-X** [Lelik13a/Zabbix-Logstash#1]
I have checked all logstash versions and this key does not exist in any API.  what is the exact logstash version you are using?

**Comment by Lelik13a** [comment]
```
# curl -s "http://localhost:9600/_node/stats/events?pretty"
{
  "host" : "host.name",
  "version" : "7.8.0",
  "http_address" : "127.0.0.1:9600",
  "id" : "6083075f-41d0-444a-a885-2e687c576837",
  "name" : "name.name",
  "ephemeral_id" : "68c98e33-f2b8-4adf-a1f1-a1d56692ae58",
  "status" : "green",
  "snapshot" : false,
  "pipeline" : {
    "workers" : 4,
    "batch_size" : 75,
    "batch_delay" : 50
  },
  "events" : {
    "in" : 131778262,
    "filtered" : 131767916,
    "out" : 131767916,
    "duration_in_millis" : 156608249,
    "queue_push_duration_in_millis" : 6501768
  }
}
```

**Comment by Lelik13a** [comment]
I changed template for use heartbeat with "discard unchanged" for logstash.version.
Otherwise the value is not displayed in the latest data.

**Comment by Protocol-X** [comment]
the template looks like it tries to get the data from jvm stats.

Also i notice piplines are not populating any data , does not show in resent data at all even if i choose to show no data.

When i use zabbix_get i see data returned.  So it doesnt appear to be an issue with setup or config, maybe something on zabbix.  I am using 4.4


sudo zabbix_get -s localhost -p10050 -k "logstash.pipelines.discovery"
sudo zabbix_get -s localhost -p10050 -k "logstash.pipelines.stages.discovery[*]"

![image](https://user-images.githubusercontent.com/98375/89423449-82a65000-d704-11ea-8abc-830743004f1b.png)

**Comment by Protocol-X** [comment]
I can execute the item manually using test, and i changed the raw storage to 1d to ensure data was being collected and it works fine.    Is there supposed to be a trigger for these that is missing?   Something is preventying the discoveryrules/ item prototypes from working

**Comment by Lelik13a** [comment]
the trigger has not been done yet, but it will be :)

**Comment by Protocol-X** [comment]
I was able to track down and resolve the issue.  The python scripts are incorrect.  You have them returning tuples, and zabbix is looking for JSON..  Once i altered the script to return the json instead of the tuple all of the issues corrected.  The only remainin issue is status.  Not sure why mine does not return that value, but it appears to be a LS issue and not an issue on yours.
